base_url = "https://ubnt-intrepid.netlify.com"
title = "missing documentation for life"
description = """
My blog for technical topics.
"""

compile_sass = true
highlight_code = true
highlight_theme = "ayu-light"
build_search_index = true
theme = "zulma"

taxonomies = [
  { name = "tags", rss = true },
  { name = "categories", rss = true },
]

[extra]
zulma_title = "missing documentation for life"
zulma_brand = { text = "missing documentation for life" }
zulma_menu = [
  { name = "Home", url = "$BASE_URL" },
  #{ name = "About", url = "$BASE_URL/about" },
  { name = "Tags", url = "$BASE_URL/tags" },
  { name = "Categories", url = "$BASE_URL/categories" },
]

use_embedly = true
