base_url = "https://ubnt-intrepid.netlify.com"
title = "missing documentation for life"
description = """
My blog for technical topics.
"""

compile_sass = true
highlight_code = true
highlight_theme = "ayu-light"
build_search_index = true

taxonomies = [
  { name = "tags", paginate_by = 5, rss = true },
  { name = "categories", paginate_by = 5, rss = true },
]

[extra]
use_embedly = true
utterances = { repo = "ubnt-intrepid/site" }
bulmaswatch_theme = "united"
