[package]
name = "hello"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
polyfuse = "0.2"
polyfuse-tokio = "0.1"

anyhow = "1"
tokio = { version = "0.2", features = [ "full" ] }
tracing = "0.1"
tracing-subscriber = "0.1"
